version: '3'

services:
  tinyproxy:
    image: dannydirect/tinyproxy:latest
    container_name: tinyproxy
    restart: unless-stopped
    ports:
      - "${PROXY_PORT}:8888"
    environment:
      - BASICAUTH=${PROXY_USER}:${PROXY_PASSWORD}
      - TZ=${TIMEZONE}
    command: ANY
    networks:
      - proxy-network

networks:
  proxy-network:
    driver: bridge