version: '3'

services:
  tinyproxy:
    image: monokal/tinyproxy:latest
    container_name: tinyproxy
    restart: unless-stopped
    ports:
      - "${PROXY_PORT}:8888"
    environment:
      - TZ=${TIMEZONE}
    command: -p 8888 -a ${PROXY_USER}:${PROXY_PASSWORD} ANY
    networks:
      - proxy-network

networks:
  proxy-network:
    driver: bridge